config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'staticpages/home'
  root :to => 'staticpages#home'
  
  
  resources :groups do
    resources :gyears
  end
  
  
  resources :members
  
  resources :groups
  
  resources :membergroups

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, :presence => true
  
  has_many :membergroups
  has_many :members, :through => :membergroups
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates :first_name, :presence => true
  
  has_many :membergroups
  has_many :groups, :through => :membergroups
  
end

app/models/membergroup.rb
class Membergroup < ActiveRecord::Base
  
  belongs_to :member
  belongs_to :group
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @member = Member.new
    
    @members = Member.all
    
    @member_groups = Membergroup.all
  end

  # GET /groups/new
  def new
    @group = Group.new
    
    @groups = Group.all
    
    @members = Member.all
    
    @group_member = @group.membergroups.build
  end

  # GET /groups/1/edit
  def edit
    
  
 end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    params[:member][:id].each do |group|
      if !group.empty?
        @group.membergroups.build(:member_id => group)
      end
    end

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
    
    def year
      
    end
end

app/controllers/gyears_controller.rb
class GyearsController < ApplicationController
  
  def show
    @member_groups = Membergroup.all
    @members = Member.all
    
    @group_id = params[:group_id].to_i
    @year = params[:id].to_i
   
  end
end

app/controllers/membergroups_controller.rb
class MembergroupsController < ApplicationController

def index
    @membergroups = Membergroup.all
    @membergroup = Membergroup.new
    
    
    @group = Group.new  
    @groups = Group.all 
    @members = Member.all
    @group_member = @group.membergroups.build
  end
  
  def new
    
  end
  
  def show
    
  end
  
  def create 
     
    @group_id = params[:group][:id]
    @groupyear = params[:date][:groupyear]
   
    params[:member][:id].each do |group|
      if !group.empty?
        Membergroup.new(:member_id => group, :groupyear => @groupyear, :group_id => @group_id).save
      end
    end
     
     
    
    
    respond_to do |format|
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
    end
  end
 
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
    
    @group = Group.new
    
    @groups = Group.all
    
    @member_groups = Membergroup.all
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)


    
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :insert, :last_name, :dob, :phone, :adress, :adressNr, :zipcode, :membershipYear)
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  
  #homepage
  def home
     render 'staticpages/home' 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/gyears_helper.rb
module GyearsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/membergroups_helper.rb
module MembergroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .row
    .small-5.columns
      .field
        = f.label :naam
        = f.text_field :name
  .row
    .small-6.columns
    .small-4.columns
      = f.submit "aanmaken", :class => "button radius"
= link_to 'terug', groups_path, :class => "button radius"

app/views/groups/edit.html.haml
%h1 commissies aanpassen
= render 'form'
= link_to 'tonen', @group
|
\#{link_to 'terug', groups_path}

app/views/groups/index.html.haml
.row
  .small-4.columns
    %table
      %thead
        %tr
          %th{:width => "190"} Comissies
      %tbody
        - @groups.each do |group|
          %tr
            %td
              = link_to group.name, group
              = link_to image_tag("delete.png", alt: "verwijderen", size: "20"), group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "icon-align"
              = link_to image_tag("edit.png", alt: "aanpassen", size: "20"), edit_group_path(group), :class => "icon-align"
%br
  .row
    .small-2.columns
    .small-3.columns
      = link_to 'nieuwe commissie', new_group_path, :class => "button radius"

app/views/groups/new.html.haml
= render 'form'

app/views/groups/show.html.haml
/ code om alle jaren uit de jointable in een array te zetten, dubbele te verwijderen en sorteren
- @years = Array.new
- @member_groups.each do |aa|
  - if aa.groupyear.nil? == false && aa.group_id == @group.id
    - @years.push(aa.groupyear)
- @years.sort
.row
  .small-4.columns
    %p.title
      = @group.name
    %br/
.row
  .small-4.columns
    %table
      %thead
        %tr
          %th{:width => "190"} Jaar
      %tbody
        - @years.uniq.each do |cc|
          %tr
            %td
              = link_to cc, group_gyear_path(@group, cc)
              %br/
  %div
    .row
      .small-6.columns
      .small-6.columns
        = link_to 'terug', groups_path, :class =>"button radius"

app/views/gyears/show.html.haml
.row
  .small-12.columns
    %p
      groep #{@group_id}
      %br/
      jaar #{@year}
      %br/
      %strong deelnemers:
      %br/
      - @member_groups.each do |aa|
        - if aa.group_id == @group_id && aa.groupyear == @year
          - @members.each do |bb|
            - if bb.id == aa.member_id
              = link_to bb.first_name, member_path(bb.id)

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    = favicon_link_tag ''
    .contain-to-grid
      %nav.top-bar{"data-topbar" => "", :role => "navigation"}
        %section.top-bar-section
          / Right Nav Section
          %ul.right
            /
              dropdown, werkt niet
              <haml:silent>			 if user_signed_in?
              </haml:silent><haml:block>			       		<li class="has-dropdown">
              <haml:loud> link_to current_user.email, &amp;quot;#&amp;quot;  </haml:loud>
              <ul class="dropdown">
              <li><a href="http://localhost:3000/users/edit"><haml:loud> link_to &amp;#39;Edit profile&amp;#39;, edit_user_registration_path </haml:loud></a></li>
              <li><haml:loud> link_to &amp;quot;Logout&amp;quot;, destroy_user_session_path, method: :delete </haml:loud></li>
              </ul>
              </li>
              </haml:block><haml:silent>			         else
              </haml:silent><haml:block>			          <li class="active"><haml:loud> link_to &amp;quot;Log in&amp;quot;, new_user_session_path </haml:loud></li>
              <li class="active"><haml:loud> link_to &amp;quot;Sign up&amp;quot;, new_user_registration_path </haml:loud></li>
              </haml:block>
            - if user_signed_in?
              %li.active= link_to "Profiel wijzigen", edit_user_registration_path
              %li.active= link_to "Uitloggen", destroy_user_session_path, method: :delete
            - else
              %li.active= link_to "Inloggen", new_user_session_path
              %li.active= link_to "Account aanmaken", new_user_registration_path
          / Left Nav Section
          %ul.left
            <li
            - if controller.controller_name=='staticpages'
              class="active"
            >#{link_to 'Home', staticpages_home_path}
            - if user_signed_in?
              <li
              - if controller.controller_name=='members'
                class="active"
              > #{link_to 'Leden', members_path}
              <li
              - if controller.controller_name=='groups'
                class="active"
              > #{link_to 'Commissies', groups_path}
              <li
              - if controller.controller_name=='membergroups'
                class="active"
              > #{link_to 'koppelen', membergroups_path}
  %body
    %br/
    = yield
    = javascript_include_tag "application"

app/views/membergroups/_form.html.haml
= form_for (@membergroup) do |f|
  .row
    .small-4.columns
      .field
        = f.label :commissie
        = collection_select(:group, :id, @groups, :id, :name , {}, {:multiple => false})
    .small-4.columns.end
      .field
        = f.label :jaar
        = select_year(Date.today, :start_year => Time.now.year, :end_year => Time.now.year - 95, :field_name => 'groupyear' )
  .row
    .small-4.columns
      .field
        = fields_for(@group_member) do |ab|
          = ab.label :leden
          = collection_select(:member, :id, @members, :id, :first_name , {}, {:multiple => true, :class => "memberselect"})
  .row
    = f.submit "koppelen", :class => "button radius"

app/views/membergroups/index.html.haml
= render 'form'

app/views/members/_form.html.haml
= form_for(@member) do |f|
  - if @member.errors.any?
    #error_explanation
      %h2
        = pluralize(@member.errors.count, "error")
        prohibited this member from being saved:
      %ul
        - @member.errors.full_messages.each do |message|
          %li= message
  .row
    .small-4.columns
      .field
        = f.label :voornaam
        = f.text_field :first_name
    .small-4.columns
      .field
        = f.label :tussenvoegsel
        = f.text_field :insert
    .small-4.columns
      .field
        = f.label :achternaam
        = f.text_field :last_name
    .small-4.columns.end
      .field
        = f.label :geboorte_datum
        = f.date_select :dob, :order => [:day, :month, :year]
  .row
    .small-6.columns
      .field
        = f.label :adres
        = f.text_field :adress
    .small-3.columns
      .field
        = f.label :huis_nr
        = f.number_field :adressNr
    .small-3.columns
      .field
        = f.label :postcode
        = f.text_field :zipcode
    .small-4.columns
      .field
        Plaats moet nog!
        /
          <haml:loud> f.label :telefoon_nr </haml:loud>
          <haml:loud> f.number_field :phone </haml:loud>
    .small-4.columns
      .field
        = f.label :telefoon_nr
    .small-4.columns
      .field
        = f.label :jaar_van_lidwording
        = f.number_field :membershipYear
  .row
    .small-6.columns
    .small-4.columns
      - if current_page?(controller: 'members', action: 'new')
        = f.submit "maak lid aan", :class => "button radius"
      - elsif current_page?(controller: 'members', action: 'edit')
        = f.submit "pas lid aan", :class => "button radius"
      = link_to 'terug', members_path, :class => "button radius"

app/views/members/edit.html.haml
= render 'form'

app/views/members/index.html.haml
.row
  .small-3.columns
    %table
      %thead
        %tr
          %th{:width => "300"} Leden lijst
      %tbody
        - @members.each do |member|
          %tr
            %td
              = link_to member.first_name, member
              = link_to image_tag("delete.png", alt: "verwijderen", size: "20"), member, method: :delete, data: { confirm: 'Are you sure?' }, :class => "icon-align"
              = link_to image_tag("edit.png", alt: "aanpassen", size: "20"), edit_member_path(member), :class => "icon-align"
%br
  .row
    .small-2.columns
    .small-2.columns
      = link_to 'nieuw lid', new_member_path, :class => "button radius"

app/views/members/new.html.haml
= render 'form'

app/views/members/show.html.haml
.row
  .small-4.columns
    %p
      %strong naam:
      %br/
      %strong geboorte datum:
      %br/
      %strong telefoon nummer:
      %br/
      %strong Adres:
      %br/
      %strong postcode:
      %br/
      %strong plaats
      %br/
      %strong jaar van lidwording:
      %br/
  .small-4.columns.end
    %p
      = @member.first_name
      - if @member.insert
        = @member.insert
      = @member.last_name
      %br/
      - if @member.dob
        = @member.dob
        %br/
      - else
        niet bekend
        %br/
      - if @member.phone
        = @member.phone
        %br/
      - else
        niet bekend
        %br/
      - if @member.adress
        = @member.adress
        - if @member.adressNr
          = @member.adressNr
          %br/
        - else
          %br/
      - else
        niet bekend
        %br/
      - if @member.zipcode
        = @member.zipcode
        %br/
      - else
        niet bekend
        %br/
      / hier moet nog code komen voor woonplaats
      niet bekend
      %br/
      - if @member.membershipYear
        = @member.membershipYear
        %br/
      - else
        niet bekend
        %br/
  .small-12.columns
    %strong Heeft deelgenomen aan de volgende commissies:
    %br/
    - @member_groups.each do |aa|
      - if aa.member_id == @member.id
        - @groups.each do |bb|
          - if bb.id == aa.group_id
            = link_to bb.name, group_path(bb.id)
            = aa.groupyear
%br/
%br/
%br/
.row
  .small-6.columns
  .small-6.columns
    = link_to 'aanpassen', edit_member_path(@member), :class => "button radius"
    = link_to 'verwijderen', @member, method: :delete, data: { confirm: 'Are you sure?' },:class => "button radius"
    = link_to 'terug', members_path, :class => "button radius"

app/views/staticpages/home.html.haml
.row
  %p Welkom op de homepage
.row.blue
  .large-6.columns
    %h4 Over de applicatie
    %p
      Deze applicatie is ontworpen en ontwikkeld voor studenten en sportverenigingen welke te maken
      hebben met ledenadministratie en commissiebeheer. Met deze applicatie kan je leden en commissies toevoegen
      en deze aan elkaar koppelen
  .large-6.columns
    %h4 Functionaliteiten
    %li Account aanmaken
    %li Inloggen
    %li Leden toevoegen
    %li Leden bewerken
    %li Leden verwijderen
    %li Commissies toevoegen
    %li Commissie bewerken
    %li Commissie verwijderen
    %li Leden aan commissies koppelen
.row.blue
  .large-4.columns.blue
    %h4 Wat moet er nog gebeuren
    %li Leden uit commissies verwijderen, werkend maken
    
		